# https://geshan.com.np/blog/2021/12/docker-postgres/
version: '3.3'
services:
  postgres:
    container_name: pg13_1313
    image: postgres:13
    restart: unless-stopped
    ports:
      - "1313:5432"
    environment:
      - POSTGRES_DB=appdata
      - POSTGRES_USER=appadmin
      - POSTGRES_PASSWORD=12345678
    volumes: 
      - db:/var/lib/postgresql/data
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
# https://earthly.dev/blog/docker-volumes/
volumes:
  db:
    driver: local